### PR TITLE
Added order_id to collection query

### PR DESCRIPTION
**Pull request by julian-van-drielen**
By querying directly on parent_item_id results in a full table scan every time. This causes a severe performance issue when the sales_order_item contains millions of records.

By also querying on order_id, results in just scanning all items in a single order, as this field is indexed.

### CODE REVIEW

**Comment by eduard13** [comment]
Hi @julian-van-drielen, thank you for your suggestions, we will definitely include them into our next release

**Comment by julian-van-drielen** [comment]
Hi @eduard13,

I've done this now, however, build is still failing.

**Comment by eduard13** [comment]
Hi @julian-van-drielen, we'll process and deliver your PR internally and release within the next upcoming release.
In the meantime, feel free to apply these changes as a patch.

Thank you for your great contribution.

**Comment by eduard13** [comment]
Hi @julian-van-drielen, these changes were successfully added into [1.0.0](https://github.com/exponea/bloomreach-magento2-integration/releases/tag/1.0.0) release.

Thank you for your contribution

Resolving this PR.

**Pull request closed without merging**
